import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const { email, totalMonthlySavings, totalAnnualSavings, isHighSavings } = body

    const { error } = await resend.emails.send({
      from: 'SpendLens <onboarding@resend.dev>',
      to: email,
      subject: 'Your AI Spend Audit from SpendLens',
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #059669;">Your SpendLens Audit</h1>
          
          ${totalMonthlySavings > 0 ? `
            <p>Great news! Based on your audit, you could save:</p>
            <h2 style="color: #059669;">$${totalMonthlySavings.toFixed(0)}/month</h2>
            <p>That's <strong>$${totalAnnualSavings.toFixed(0)} per year</strong>.</p>
          ` : `
            <p>Good news — your AI stack looks well optimised!</p>
            <p>We'll notify you when new savings opportunities apply to your tools.</p>
          `}

          ${isHighSavings ? `
            <div style="background: #111827; color: white; padding: 24px; border-radius: 12px; margin: 24px 0;">
              <h3 style="color: #34d399; margin-top: 0;">Credex can help you save even more</h3>
              <p style="color: #9ca3af;">At your spend level, Credex discounted AI credits could save you an additional 20-40%.</p>
              <a href="https://credex.rocks" style="background: #10b981; color: white; padding: 12px 24px; border-radius: 24px; text-decoration: none; display: inline-block;">Book a Credex Consultation</a>
            </div>
          ` : ''}

          <p style="color: #6b7280; font-size: 14px;">
            This audit was generated by SpendLens — free AI spend auditing for startups.
          </p>
          <a href="https://spendlens.vercel.app" style="color: #059669;">spendlens.vercel.app</a>
        </div>
      `,
    })

    if (error) {
      console.error('Resend error:', error)
      return NextResponse.json({ error: 'Failed to send email' }, { status: 500 })
    }

    return NextResponse.json({ success: true })
  } catch (error) {
    console.error('Email error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}